import {
  Heart,
  Syringe as Ring,
  FileText,
  TrendingUp,
  Users,
  Lightbulb,
  Wallet,
  Star,
} from "lucide-react";

export const categories = [
  { id: "love", name: "연애", icon: Heart, description: "사랑과 관계의 흐름" },
  {
    id: "marriage",
    name: "결혼",
    icon: Ring,
    description: "결혼과 가족의 미래",
  },
  { id: "career", name: "직업", icon: FileText, description: "커리어와 성장" },
  {
    id: "business",
    name: "사업",
    icon: TrendingUp,
    description: "사업과 투자",
  },
  {
    id: "relationships",
    name: "인간관계",
    icon: Users,
    description: "주변 사람들과의 관계",
  },
  {
    id: "growth",
    name: "자기성장",
    icon: Lightbulb,
    description: "내면의 성장과 발전",
  },
  {
    id: "finance",
    name: "재정/소비",
    icon: Wallet,
    description: "돈과 소비 패턴",
  },
  { id: "timing", name: "운/타이밍", icon: Star, description: "운세와 타이밍" },
];

export const subcategories = {
  love: [
    {
      id: "start",
      name: "새로운 시작",
      description: "새로운 만남이나 관계의 시작",
    },
    {
      id: "current",
      name: "현재 진단",
      description: "지금 관계의 상태와 흐름",
    },
    { id: "partner", name: "상대 속마음", description: "상대방의 진심과 감정" },
    {
      id: "future",
      name: "앞으로 흐름",
      description: "관계의 미래와 발전 방향",
    },
    {
      id: "action",
      name: "나의 행동",
      description: "내가 취해야 할 행동과 태도",
    },
  ],
  marriage: [
    { id: "timing", name: "결혼 타이밍", description: "결혼하기 좋은 시기" },
    {
      id: "partner",
      name: "결혼 상대",
      description: "미래의 배우자에 대한 통찰",
    },
    { id: "family", name: "가족 관계", description: "시댁, 친정과의 관계" },
    {
      id: "preparation",
      name: "결혼 준비",
      description: "결혼 준비 과정의 조언",
    },
  ],
  career: [
    {
      id: "change",
      name: "직업 변화",
      description: "이직이나 전직에 대한 조언",
    },
    { id: "promotion", name: "승진/발전", description: "현재 직장에서의 성장" },
    {
      id: "workplace",
      name: "직장 내 관계",
      description: "동료, 상사와의 관계",
    },
    { id: "skills", name: "역량 개발", description: "필요한 스킬과 능력" },
  ],
  business: [
    { id: "startup", name: "창업", description: "새로운 사업 시작" },
    { id: "investment", name: "투자", description: "투자 기회와 위험" },
    {
      id: "partnership",
      name: "파트너십",
      description: "사업 파트너와의 관계",
    },
    { id: "growth", name: "사업 확장", description: "사업 성장과 확장" },
  ],
  relationships: [
    { id: "friends", name: "친구 관계", description: "친구들과의 관계 개선" },
    { id: "family", name: "가족 관계", description: "가족 구성원과의 관계" },
    {
      id: "conflicts",
      name: "갈등 해결",
      description: "인간관계의 갈등과 해결",
    },
    {
      id: "networking",
      name: "새로운 인맥",
      description: "새로운 사람들과의 만남",
    },
  ],
  growth: [
    { id: "purpose", name: "인생 목표", description: "삶의 방향과 목적" },
    { id: "habits", name: "습관 개선", description: "좋은 습관 만들기" },
    { id: "mindset", name: "마음가짐", description: "긍정적인 사고방식" },
    { id: "healing", name: "내면 치유", description: "상처와 트라우마 극복" },
  ],
  finance: [
    { id: "saving", name: "저축", description: "돈 모으기와 절약" },
    { id: "spending", name: "소비 패턴", description: "지출 습관 개선" },
    { id: "investment", name: "재테크", description: "투자와 자산 관리" },
    { id: "debt", name: "부채 관리", description: "빚 정리와 관리" },
  ],
  timing: [
    {
      id: "decision",
      name: "결정 타이밍",
      description: "중요한 결정을 내릴 시기",
    },
    { id: "opportunity", name: "기회", description: "다가올 기회와 준비" },
    { id: "luck", name: "운세", description: "전반적인 운의 흐름" },
    { id: "caution", name: "주의사항", description: "조심해야 할 것들" },
  ],
};

export const fullTarotDeck = [
  // Major Arcana (22 cards)
  {
    name: "The Fool",
    koreanName: "바보",
    meaning: "새로운 시작",
    description: "용기를 내어 새로운 여정을 시작할 때입니다.",
  },
  {
    name: "The Magician",
    koreanName: "마법사",
    meaning: "의지와 창조",
    description: "당신의 의지력으로 현실을 창조할 수 있습니다.",
  },
  {
    name: "The High Priestess",
    koreanName: "여교황",
    meaning: "직감과 신비",
    description: "내면의 목소리에 귀 기울여보세요.",
  },
  {
    name: "The Empress",
    koreanName: "여황제",
    meaning: "풍요와 창조",
    description: "풍요로운 에너지가 당신을 둘러싸고 있습니다.",
  },
  {
    name: "The Emperor",
    koreanName: "황제",
    meaning: "권위와 안정",
    description: "강한 의지로 상황을 통제할 수 있습니다.",
  },
  {
    name: "The Hierophant",
    koreanName: "교황",
    meaning: "전통과 지혜",
    description: "전통적인 방법이 해답을 줄 것입니다.",
  },
  {
    name: "The Lovers",
    koreanName: "연인",
    meaning: "사랑과 선택",
    description: "중요한 선택의 순간이 다가왔습니다.",
  },
  {
    name: "The Chariot",
    koreanName: "전차",
    meaning: "의지와 승리",
    description: "강한 의지로 목표를 달성할 수 있습니다.",
  },
  {
    name: "Strength",
    koreanName: "힘",
    meaning: "내면의 힘",
    description: "부드러운 힘으로 어려움을 극복하세요.",
  },
  {
    name: "The Hermit",
    koreanName: "은둔자",
    meaning: "성찰과 지혜",
    description: "혼자만의 시간을 통해 답을 찾으세요.",
  },
  {
    name: "Wheel of Fortune",
    koreanName: "운명의 바퀴",
    meaning: "변화와 운명",
    description: "운명의 변화가 시작되었습니다.",
  },
  {
    name: "Justice",
    koreanName: "정의",
    meaning: "균형과 공정",
    description: "공정한 판단이 필요한 시점입니다.",
  },
  {
    name: "The Hanged Man",
    koreanName: "매달린 사람",
    meaning: "희생과 깨달음",
    description: "새로운 관점으로 상황을 바라보세요.",
  },
  {
    name: "Death",
    koreanName: "죽음",
    meaning: "변화와 재생",
    description: "끝은 새로운 시작을 의미합니다.",
  },
  {
    name: "Temperance",
    koreanName: "절제",
    meaning: "조화와 균형",
    description: "균형 잡힌 접근이 필요합니다.",
  },
  {
    name: "The Devil",
    koreanName: "악마",
    meaning: "유혹과 속박",
    description: "자신을 속박하는 것들을 인식하세요.",
  },
  {
    name: "The Tower",
    koreanName: "탑",
    meaning: "파괴와 해방",
    description: "급격한 변화가 새로운 기회를 가져올 것입니다.",
  },
  {
    name: "The Star",
    koreanName: "별",
    meaning: "희망과 영감",
    description: "어둠 속에서도 빛을 잃지 않는 희망의 메시지입니다.",
  },
  {
    name: "The Moon",
    koreanName: "달",
    meaning: "직감과 신비",
    description: "내면의 목소리에 귀 기울이고 직감을 믿어보세요.",
  },
  {
    name: "The Sun",
    koreanName: "태양",
    meaning: "성공과 기쁨",
    description: "밝은 에너지가 당신의 삶을 비추고 있습니다.",
  },
  {
    name: "Judgement",
    koreanName: "심판",
    meaning: "각성과 부활",
    description: "새로운 각성의 순간이 다가왔습니다.",
  },
  {
    name: "The World",
    koreanName: "세계",
    meaning: "완성과 성취",
    description: "목표 달성과 새로운 시작을 의미합니다.",
  },

  // Minor Arcana - Wands (14 cards)
  {
    name: "Ace of Wands",
    koreanName: "완드 에이스",
    meaning: "새로운 열정",
    description: "창조적 에너지가 폭발할 때입니다.",
  },
  {
    name: "Two of Wands",
    koreanName: "완드 2",
    meaning: "계획과 준비",
    description: "미래를 위한 계획을 세울 시간입니다.",
  },
  {
    name: "Three of Wands",
    koreanName: "완드 3",
    meaning: "확장과 성장",
    description: "당신의 노력이 결실을 맺기 시작합니다.",
  },
  {
    name: "Four of Wands",
    koreanName: "완드 4",
    meaning: "축하와 안정",
    description: "성취를 축하하고 안정을 누리세요.",
  },
  {
    name: "Five of Wands",
    koreanName: "완드 5",
    meaning: "경쟁과 갈등",
    description: "건설적인 경쟁을 통해 성장하세요.",
  },
  {
    name: "Six of Wands",
    koreanName: "완드 6",
    meaning: "승리와 인정",
    description: "당신의 노력이 인정받을 것입니다.",
  },
  {
    name: "Seven of Wands",
    koreanName: "완드 7",
    meaning: "방어와 도전",
    description: "자신의 입장을 굳건히 지키세요.",
  },
  {
    name: "Eight of Wands",
    koreanName: "완드 8",
    meaning: "빠른 진전",
    description: "상황이 빠르게 발전할 것입니다.",
  },
  {
    name: "Nine of Wands",
    koreanName: "완드 9",
    meaning: "인내와 끈기",
    description: "마지막까지 포기하지 마세요.",
  },
  {
    name: "Ten of Wands",
    koreanName: "완드 10",
    meaning: "부담과 책임",
    description: "무거운 짐이지만 곧 끝날 것입니다.",
  },
  {
    name: "Page of Wands",
    koreanName: "완드 페이지",
    meaning: "열정적 메시지",
    description: "새로운 기회의 소식이 들려올 것입니다.",
  },
  {
    name: "Knight of Wands",
    koreanName: "완드 기사",
    meaning: "행동과 모험",
    description: "과감한 행동이 필요한 시점입니다.",
  },
  {
    name: "Queen of Wands",
    koreanName: "완드 여왕",
    meaning: "자신감과 매력",
    description: "당신의 매력과 자신감을 발휘하세요.",
  },
  {
    name: "King of Wands",
    koreanName: "완드 왕",
    meaning: "리더십과 비전",
    description: "강력한 리더십으로 목표를 달성하세요.",
  },

  // Minor Arcana - Cups (14 cards)
  {
    name: "Ace of Cups",
    koreanName: "컵 에이스",
    meaning: "새로운 감정",
    description: "사랑과 감정의 새로운 시작입니다.",
  },
  {
    name: "Two of Cups",
    koreanName: "컵 2",
    meaning: "사랑과 파트너십",
    description: "깊은 유대감이 형성될 것입니다.",
  },
  {
    name: "Three of Cups",
    koreanName: "컵 3",
    meaning: "우정과 축하",
    description: "친구들과 함께 기쁨을 나누세요.",
  },
  {
    name: "Four of Cups",
    koreanName: "컵 4",
    meaning: "무관심과 지루함",
    description: "새로운 기회를 놓치지 마세요.",
  },
  {
    name: "Five of Cups",
    koreanName: "컵 5",
    meaning: "실망과 슬픔",
    description: "상실감을 극복하고 앞으로 나아가세요.",
  },
  {
    name: "Six of Cups",
    koreanName: "컵 6",
    meaning: "향수와 순수",
    description: "과거의 좋은 기억이 위안을 줄 것입니다.",
  },
  {
    name: "Seven of Cups",
    koreanName: "컵 7",
    meaning: "환상과 선택",
    description: "현실적인 선택을 하는 것이 중요합니다.",
  },
  {
    name: "Eight of Cups",
    koreanName: "컵 8",
    meaning: "포기와 떠남",
    description: "때로는 떠나는 것이 답일 수 있습니다.",
  },
  {
    name: "Nine of Cups",
    koreanName: "컵 9",
    meaning: "만족과 성취",
    description: "소원이 이루어지는 행복한 시간입니다.",
  },
  {
    name: "Ten of Cups",
    koreanName: "컵 10",
    meaning: "행복과 완성",
    description: "가족과 함께하는 완전한 행복입니다.",
  },
  {
    name: "Page of Cups",
    koreanName: "컵 페이지",
    meaning: "감성적 메시지",
    description: "마음에서 우러나는 메시지에 주목하세요.",
  },
  {
    name: "Knight of Cups",
    koreanName: "컵 기사",
    meaning: "로맨스와 이상",
    description: "로맨틱한 제안이나 기회가 올 것입니다.",
  },
  {
    name: "Queen of Cups",
    koreanName: "컵 여왕",
    meaning: "직감과 공감",
    description: "직감을 믿고 타인을 이해하세요.",
  },
  {
    name: "King of Cups",
    koreanName: "컵 왕",
    meaning: "감정의 균형",
    description: "감정을 잘 다스리며 현명하게 행동하세요.",
  },

  // Minor Arcana - Swords (14 cards)
  {
    name: "Ace of Swords",
    koreanName: "검 에이스",
    meaning: "새로운 아이디어",
    description: "명확한 사고로 문제를 해결하세요.",
  },
  {
    name: "Two of Swords",
    koreanName: "검 2",
    meaning: "결정의 어려움",
    description: "신중한 판단이 필요한 시점입니다.",
  },
  {
    name: "Three of Swords",
    koreanName: "검 3",
    meaning: "상처와 슬픔",
    description: "마음의 상처를 치유할 시간이 필요합니다.",
  },
  {
    name: "Four of Swords",
    koreanName: "검 4",
    meaning: "휴식과 명상",
    description: "잠시 쉬면서 마음을 정리하세요.",
  },
  {
    name: "Five of Swords",
    koreanName: "검 5",
    meaning: "갈등과 패배",
    description: "때로는 물러서는 것이 지혜입니다.",
  },
  {
    name: "Six of Swords",
    koreanName: "검 6",
    meaning: "이동과 변화",
    description: "어려운 시기를 벗어나 새로운 곳으로 향하세요.",
  },
  {
    name: "Seven of Swords",
    koreanName: "검 7",
    meaning: "속임과 전략",
    description: "신중하게 계획을 세우고 행동하세요.",
  },
  {
    name: "Eight of Swords",
    koreanName: "검 8",
    meaning: "제약과 속박",
    description: "스스로 만든 제약에서 벗어나세요.",
  },
  {
    name: "Nine of Swords",
    koreanName: "검 9",
    meaning: "불안과 걱정",
    description: "과도한 걱정은 도움이 되지 않습니다.",
  },
  {
    name: "Ten of Swords",
    koreanName: "검 10",
    meaning: "끝과 배신",
    description: "고통스러운 끝이지만 새로운 시작의 전조입니다.",
  },
  {
    name: "Page of Swords",
    koreanName: "검 페이지",
    meaning: "호기심과 학습",
    description: "새로운 정보나 소식에 주의를 기울이세요.",
  },
  {
    name: "Knight of Swords",
    koreanName: "검 기사",
    meaning: "성급함과 행동",
    description: "신중함보다는 빠른 행동이 필요합니다.",
  },
  {
    name: "Queen of Swords",
    koreanName: "검 여왕",
    meaning: "명확함과 독립",
    description: "명확한 의사소통과 독립적 사고가 필요합니다.",
  },
  {
    name: "King of Swords",
    koreanName: "검 왕",
    meaning: "지성과 권위",
    description: "논리적 사고로 상황을 판단하세요.",
  },

  // Minor Arcana - Pentacles (14 cards)
  {
    name: "Ace of Pentacles",
    koreanName: "펜타클 에이스",
    meaning: "새로운 기회",
    description: "물질적 성공의 기회가 다가옵니다.",
  },
  {
    name: "Two of Pentacles",
    koreanName: "펜타클 2",
    meaning: "균형과 적응",
    description: "여러 일을 균형 있게 처리하세요.",
  },
  {
    name: "Three of Pentacles",
    koreanName: "펜타클 3",
    meaning: "협력과 기술",
    description: "팀워크를 통해 목표를 달성하세요.",
  },
  {
    name: "Four of Pentacles",
    koreanName: "펜타클 4",
    meaning: "안정과 보수",
    description: "안정을 추구하되 너무 보수적이지는 마세요.",
  },
  {
    name: "Five of Pentacles",
    koreanName: "펜타클 5",
    meaning: "궁핍과 어려움",
    description: "어려운 시기이지만 도움의 손길이 있습니다.",
  },
  {
    name: "Six of Pentacles",
    koreanName: "펜타클 6",
    meaning: "나눔과 균형",
    description: "주고받는 균형을 맞추는 것이 중요합니다.",
  },
  {
    name: "Seven of Pentacles",
    koreanName: "펜타클 7",
    meaning: "인내와 평가",
    description: "지금까지의 노력을 평가해볼 시간입니다.",
  },
  {
    name: "Eight of Pentacles",
    koreanName: "펜타클 8",
    meaning: "기술과 노력",
    description: "꾸준한 노력으로 실력을 향상시키세요.",
  },
  {
    name: "Nine of Pentacles",
    koreanName: "펜타클 9",
    meaning: "독립과 성취",
    description: "자립적인 성공을 이루어냈습니다.",
  },
  {
    name: "Ten of Pentacles",
    koreanName: "펜타클 10",
    meaning: "부와 유산",
    description: "물질적 풍요와 가족의 행복을 누리세요.",
  },
  {
    name: "Page of Pentacles",
    koreanName: "펜타클 페이지",
    meaning: "학습과 기회",
    description: "새로운 학습 기회나 투자 기회에 주목하세요.",
  },
  {
    name: "Knight of Pentacles",
    koreanName: "펜타클 기사",
    meaning: "성실과 인내",
    description: "꾸준하고 성실한 노력이 결실을 맺을 것입니다.",
  },
  {
    name: "Queen of Pentacles",
    koreanName: "펜타클 여왕",
    meaning: "실용과 풍요",
    description: "실용적인 접근으로 풍요로운 삶을 만드세요.",
  },
  {
    name: "King of Pentacles",
    koreanName: "펜타클 왕",
    meaning: "성공과 안정",
    description: "물질적 성공과 안정된 지위를 얻을 것입니다.",
  },
];
