import { ShapeType, ShapeConfig } from "@/types/play/draw";

export const SHAPES: Record<ShapeType, ShapeConfig> = {
  triangle: {
    name: "Triangle",
    emoji: "🔺",
    description: "Draw an equilateral triangle",
    gradient: "from-emerald-300 via-teal-300 to-cyan-300",
    shadowColor: "rgba(32, 178, 170, 0.3)",
    strokeColor: "#20B2AA",
    difficulty: 2,
  },
  square: {
    name: "Square",
    emoji: "🟦",
    description: "Draw a perfect square",
    gradient: "from-sky-300 via-blue-300 to-indigo-300",
    shadowColor: "rgba(135, 206, 235, 0.3)",
    strokeColor: "#87CEEB",
    difficulty: 2,
  },
  circle: {
    name: "Circle",
    emoji: "⭕",
    description: "Draw a perfect circle",
    gradient: "from-purple-300 via-pink-300 to-rose-300",
    shadowColor: "rgba(219, 112, 147, 0.3)",
    strokeColor: "#DDA0DD",
    difficulty: 3,
  },

  diamond: {
    name: "Diamond",
    emoji: "💎",
    description: "Draw a brilliant diamond",
    gradient: "from-cyan-200 via-sky-300 to-blue-400",
    shadowColor: "rgba(56, 189, 248, 0.3)",
    strokeColor: "#38BDF8",
    difficulty: 2,
  },
  umbrella: {
    name: "Umbrella",
    emoji: "☂️",
    description: "Draw an umbrella shape",
    gradient: "from-rose-300 via-pink-300 to-fuchsia-300",
    shadowColor: "rgba(255, 182, 193, 0.3)",
    strokeColor: "#FFB6C1",
    difficulty: 5,
  },
  star: {
    name: "Star",
    emoji: "⭐",
    description: "Draw a five-pointed star",
    gradient: "from-yellow-300 via-amber-300 to-orange-300",
    shadowColor: "rgba(251, 191, 36, 0.3)",
    strokeColor: "#FBBF24",
    difficulty: 5, // 난이도가 높음
  },
};

export const names = [
  "Luna✨",
  "Mia🌸",
  "Zoe💫",
  "Ava🦋",
  "Emma🌺",
  "Lily🌙",
  "Ruby💎",
  "Iris🌈",
  "Nova⭐",
  "Chloe🌻",
  "Maya🎀",
  "Aria🌷",
  "Sage🍃",
  "Rose🌹",
  "Jade💚",
  "Sky☁️",
  "Mila🎨",
  "Nora🌊",
  "Ella🦄",
  "Ivy🌿",
  "Hazel🌰",
  "Pearl🐚",
  "Wren🕊️",
  "Faye🧚",
  "Dara🌸",
  "Kira⚡",
  "Lila💜",
  "Naia🌊",
  "Vera🌺",
  "Zara✨",
  "Cora🌙",
  "Tara🌟",
];
export const avatars = [
  "🌸",
  "🦋",
  "🌺",
  "🌙",
  "💎",
  "🌈",
  "⭐",
  "🌻",
  "🎀",
  "🌷",
  "🍃",
  "🌹",
  "💚",
  "☁️",
  "🎨",
  "🌊",
  "🦄",
  "🌿",
  "🌰",
  "🐚",
  "🕊️",
  "🧚",
  "⚡",
  "💜",
  "✨",
];
